### ISSUE TITLE
Failed to resolve flagsmith kotlin library 

### ISSUE THREAD

**Issue by alhamw** [Flagsmith/flagsmith-kotlin-android-client#11]
I have follow the tutorial to add flagsmith to my kotlin project. But when I build my project, the IDE give this error: `Failed to resolve: com.github.Flagsmith:flagsmith-kotlin-android-client:1.0.1`

How to resolve it ? 

gz#415

**Comment by dabeeeenster** [comment]
Can you share the code/tutorial so we can try and reproduce?
