### ISSUE TITLE
Unable to resolve host "edge.api.flagsmith.com"

### ISSUE THREAD

**Issue by sbmaggarwal** [Flagsmith/flagsmith-kotlin-android-client#15]
I am integrating Flagsmith into a Kotlin Android client, and I'm experiencing an issue with retrieving feature flags. Here is the code snippet I'm using:

```kotlin
flagsmith.getFeatureFlags { result ->
    result.fold(
        onSuccess = { flagList ->
            Log.i("Flagsmith", "Current flags:")
            flagList.forEach { Log.i("Flagsmith", "- ${it.feature.name} - enabled: ${it.enabled} value: ${it.featureStateValue ?: "not set"}") }
        },
        onFailure = { err ->
            Log.e("Flagsmith", "Error getting feature flags ${err.message}", err)
        }
    )
}
```
During the initialization of Flagsmith, I didn't provide a URL. Here's the initialization code:

```kotlin
private fun initFlagsmith(context: Context) {
    flagsmith = Flagsmith(
        environmentKey = FLAGSMITH_DEVELOPMENT_KEY,
        context = context,
    )
}
```

### Error
When executing this code, I encounter the following error in the log:
```
Error getting feature flags Unable to resolve host "edge.api.flagsmith.com": No address associated with hostname
```

I'm using version 1.1.2 of the flagsmith-kotlin-android-client library:
```gradle
implementation 'com.github.Flagsmith:flagsmith-kotlin-android-client:1.1.2'
```

What can be the issue?

**Comment by dabeeeenster** [comment]
Are you able to check that the device is able to access that domain name? It looks like a DNS issue with the device etc? Are you able to reach that domain on your local device/

**Comment by matthewelwell** [comment]
@sbmaggarwal is this still an issue?

**Comment by sbmaggarwal** [comment]
This was auto-resolved when I ran the application, this can be closed.
