### ISSUE TITLE
Implement Real Time flags

### ISSUE THREAD

**Issue by matthewelwell** [Flagsmith/flagsmith-kotlin-android-client#18]
As per the JS SDK here: https://github.com/Flagsmith/flagsmith-js-client/blob/d85456e9a2c047665a58a782bed921a5a631b138/flagsmith-core.ts#L373

**Comment by gazreese** [comment]
So it looks I'll be doing the following to achieve this:

* customer sets a 'realtime' flag on the SDK on construction
* if set I'll set up a websocket to listen for events from your event source, which seem to be just timestamps for the last updated flags 
* I'll expose either a Flow<List<Flag>> or LiveData<List<Flag>> for the customer to be able to receive flag updates in an Android-esque way

If any of the above doesn't sound right @matthewelwell please let me know

**Comment by matthewelwell** [comment]
> So it looks I'll be doing the following to achieve this:
> 
> * customer sets a 'realtime' flag on the SDK on construction
> * if set I'll set up a websocket to listen for events from your event source, which seem to be just timestamps for the last updated flags
> * I'll expose either a Flow<List> or LiveData<List> for the customer to be able to receive flag updates in an Android-esque way
> 
> If any of the above doesn't sound right @matthewelwell please let me know

@gazreese yes, this all sounds correct. 

I just want to clarify one thing, however, since the terminology can get confusing. 

> * customer sets a 'realtime' flag on the SDK on construction

Do you mean here that we will add a new argument to the Flagsmith SDK constructor called `realtime`, or by 'flag' do you mean the flag entity in Flagsmith? 

To keep parity with the JS client for now, my preference is for the former, but certainly in the future, being able to provide a list of flags that should be enabled for realtime would probably be useful. For now, handling that in the customer's own logic via the `Flow<List>` or `LiveData<List>` should suffice.

**Comment by gazreese** [comment]
Yes the former @matthewelwell 👍

**Comment by matthewelwell** [comment]
Requirements have been added in a bit more detail to the parent issue [here](https://github.com/Flagsmith/flagsmith/issues/1498).

**Comment by flopshot** [comment]
Does this mean that the android SDK is in feature parity with JS sdk, as of 1.3.0?
My company is asking me to investigate Firebase alternatives for Android.
I'd like to know if this is something that can be used within the next week or so

**Comment by dabeeeenster** [comment]
There are affordances with the JS SDK that arent possible in the Android one, but we do have good support for all Flagsmith features within the Kotlin SDK yes!
