### ISSUE TITLE
deployments to jitpack aren't monitored

### ISSUE THREAD

**Issue by chadmiller** [Flagsmith/flagsmith-kotlin-android-client#60]
The instructions to use flagsmith give wrong information, indicating that it should work to use the current release version in a maven depenencty string.

Instead, the last few versions have failed packaging over on jitpack.

https://jitpack.io/com/github/Flagsmith/flagsmith-kotlin-android-client/v1.7.0/build.log

```
> Task :FlagsmithClient:bundleReleaseTestFixturesAar
> Task :FlagsmithClient:generateMetadataFileForReleasePublication
> Task :FlagsmithClient:publishReleasePublicationToMavenLocal
> Task :FlagsmithClient:publishToMavenLocal

BUILD SUCCESSFUL in 57s
62 actionable tasks: 60 executed, 2 up-to-date
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Archive: Flagsmith:FlagsmithClient:1.7.0
Publication: com.flagsmith:flagsmith-kotlin-android-client:1.7.0
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: com.flagsmith:flagsmith-kotlin-android-client:1.7.0
Found artifact: Flagsmith:FlagsmithClient:1.7.0
Found artifact: com.flagsmith:flagsmith-kotlin-android-client:1.7.0
ERROR: Time-out getting container status
Error building
```

This is a specific problem, but the larger problem is that the results aren't monitored or are not cared about.

**Comment by matthewelwell** [comment]
Hi @chadmiller , thanks for raising this, and apologies for the lack of monitoring here. We're in the process of moving everything across from jitpack to maven so it seems this build failures have slipped through. We'll take a look as soon as we can.

**Comment by matthewelwell** [comment]
@chadmiller as of version 1.7.1, all builds will be published to maven central and this should be the location used by customers from then on. We will be removing support for jitpack in the near future. Can you confirm if you're having issues using maven central and if so, please provide details?

**Comment by matthewelwell** [comment]
As mentioned above, we are no longer actively maintaining support for jitpack, all builds should now be obtained from maven central. See [here](https://central.sonatype.com/artifact/com.flagsmith/flagsmith-kotlin-android-client/overview) for details. The documentation at docs.flagsmith.com/clients/client-side/android/ has also been updated. 

If you have any further questions or comments, please let me know @chadmiller . Thanks again for raising the issue.
